### ISSUE TITLE
Unable to process custom metrics from Python functions

### ISSUE THREAD

**Issue by heitorlessa** [lumigo/SAR-async-lambda-metrics#4]
## How to reproduce

1. Create a Python Lambda function
2. Add a `print` statement : `print("MONITORING|1|Count|ColdStart|ServerlessAirline|service=test,function_name=async-python-test")`
3. Test the function

## Background

Regex itself is working, so I enabled `DEBUG=*` env var to gather some understanding and got the following clue:

```javascript
{
    "errorMessage": "Missing required key 'Value' in params.MetricData[0].Dimensions[2]",
    "errorType": "MissingRequiredParameter",
    "stackTrace": [
        "ParamValidator.fail (/var/task/node_modules/aws-sdk/lib/param_validator.js:50:37)",
        "ParamValidator.validateStructure (/var/task/node_modules/aws-sdk/lib/param_validator.js:61:14)",
        "ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:88:21)",
        "ParamValidator.validateList (/var/task/node_modules/aws-sdk/lib/param_validator.js:103:14)",
        "ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:90:21)",
        "ParamValidator.validateStructure (/var/task/node_modules/aws-sdk/lib/param_validator.js:75:14)",
        "ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:88:21)",
        "ParamValidator.validateList (/var/task/node_modules/aws-sdk/lib/param_validator.js:103:14)",
        "ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:90:21)",
        "ParamValidator.validateStructure (/var/task/node_modules/aws-sdk/lib/param_validator.js:75:14)"
    ]
}
```

**Comment by heitorlessa** [comment]
More info after making a new deployment..

```javascript
2019-09-03T20:10:59.451Z async-lambda-metrics Parsing lambda log event { id: '34957329142900575350335802714511782854710479521511440384', timestamp: 1567540852635, message: 'START RequestId: 65296afb-b652-46c4-9654-25cb96cb61e9 Version: $LATEST\n' }
2019-09-03T20:10:59.451Z 348d4e3b-434a-4bd5-b908-b6c329337fc2 { id: '34957329142900575350335802714511782854710479521511440384',
timestamp: 1567540852635,
message: 'START RequestId: 65296afb-b652-46c4-9654-25cb96cb61e9 Version: $LATEST\n' }
2019-09-03T20:10:59.455Z 348d4e3b-434a-4bd5-b908-b6c329337fc2
{
    "errorMessage": "Cannot destructure property `event` of 'undefined' or 'null'.",
    "errorType": "TypeError",
    "stackTrace": [
        "parseLambdaLogData (/var/task/functions/lib.js:57:12)",
        "Array.map (<anonymous>)",
        "_.flatMap.cwLogEvent (/var/task/functions/lib.js:136:5)",
        "arrayMap (/var/task/node_modules/lodash/lodash.js:639:23)",
        "map (/var/task/node_modules/lodash/lodash.js:9554:14)",
        "Function.flatMap (/var/task/node_modules/lodash/lodash.js:9257:26)",
        "processAll (/var/task/functions/lib.js:129:20)",
        "handler (/var/task/functions/index.js:11:8)"
    ]
}
```

Looking at the code now this is where it fails:

```javascript
	const {
		event: rawEvent,
		timestamp: timestamp
	} = event.extractedFields // extractedFields is undefined
```

**Comment by theburningmonk** [comment]
so looks like the default Lambda filter pattern doesn't match Python log lines... looks as though `print` inserts a newline in there, maybe that's what's breaking the subscription

![image](https://user-images.githubusercontent.com/546969/64273547-d2ebbf80-cf41-11e9-8f95-7337194b1df1.png)

**Comment by theburningmonk** [comment]
@heitorlessa v1.0.1 is published in us-east-1

**Comment by theburningmonk** [comment]
found a different issue with timestamps from Python log messages, fixed in v1.0.2

**Comment by theburningmonk** [comment]
tried it myself, now I'm seeing the metric from Python function

**Comment by heitorlessa** [comment]
That's awesome! Have you had a chance to test with Java and other runtimes in case they are also different?

I **guess** they follow the same format as Python

**Comment by theburningmonk** [comment]
Not yet. I can dig up some example projects I had before and try them out later.

**Comment by heitorlessa** [comment]
I've just tried that and it's now failing with this new error message:

```javascript
{
    "errorMessage": "timestamp must follow ISO8601",
    "errorType": "MalformedInput",
    "stackTrace": [
        "Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/query.js:50:29)",
        "Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)",
        "Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
        "AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "/var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
        "Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)",
        "Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}
```

Couldn't do much digging beyond that as of now but may ring a bell

**Comment by theburningmonk** [comment]
try 1.0.2, that was the timestamp issue I found after publishing 1.0.1...

**Comment by heitorlessa** [comment]
Lol. Will try that this evening :)

**Comment by heitorlessa** [comment]
Tested in London region and the real issue came down to the default **Filter Pattern** - I've updated to only capture `REPORTING` and `MONITORING`. 

Here's how it looks like now and I can see the metrics in.

```yaml
  # Subscribe new and existing CloudWatch Log groups to ship logs to Kinesis
  SubscribeLogsToProcessingStream:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:374852340823:applications/auto-subscribe-log-group-to-arn
        SemanticVersion: 1.4.0
      Parameters:
        # The ARN of the Lambda function or Kinesis stream to subscribe a newly created CloudWatch log group to
        DestinationArn: !Sub ${LogProcessingStream.Arn}
        ## Disables processing of own logs
        ExcludePrefix: 'ProcessCustomMetricsAsync' # Uncomment to override default value
        # Only subscribe to functions created for this project
        ## Otherwise we'd override all CloudWatch Logs by subscribing to our Kinesis
        Prefix: '/aws/lambda/awsserverlessairline' # Uncomment to override default value
        # Only captures REPORT and Custom Metrics log events; reduces cost and unnecessary noise
        FilterPattern: '?REPORT ?MONITORING'
```

**However**, metrics are being created with extra space - Creating another issue to separate the two.
